//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G.A.Z.SIOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventViewModels
    {
        public int ID { get; set; }
        public string Nazwa { get; set; }
        public System.DateTime Data { get; set; }
        public string Miejsce { get; set; }
        public decimal Cena_wejsciowki { get; set; }
        public string ID_organizator { get; set; }
        public string Rodzaj { get; set; }
        public decimal Opinia_value { get; set; }
        public int Udzial_count { get; set; }
        public int Zainteresowani_count { get; set; }
        public int Image_id { get; set; }
        public string Opis { get; set; }
    }
}
