//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G.A.Z.SIOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opinia
    {
        public int Id { get; set; }
        public int Urzytkownik_ { get; set; }
        public int wydarzenie { get; set; }
        public System.DateTime Czas { get; set; }
        public string Opinia1 { get; set; }
    }
}
